[package]
name = "bitcask"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true}
prost = { workspace = true }
bytes = { workspace = true }
crc32fast = { workspace = true }
parking_lot = { workspace = true }
log = { workspace = true }
memmap2 = { workspace = true }
