[package]
name = "http"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
bitcask-rs = { path = "../../bitcask-rs" }

quote = "1.0.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.96"
